### ISSUE TITLE
URLs from previously generated configurations no longer show the original configuration

### ISSUE THREAD

**Issue by jerrykan** [mozilla/ssl-config-generator#240]
When a configuration is generated it includes an URL which I assumed was essentially a permalink to be able to look at the same generated configuration again in the future, however I just just noticed that the `guidelines` parameter (any maybe others?) is ignored and only the configuration for the current guidelines are show.

To provide an example the following URLs should show slightly different `SSLCipherSuite` values:
  - https://ssl-config.mozilla.org/#server=apache&version=2.4.53&config=intermediate&openssl=1.1.1n&ocsp=false&guideline=5.6
  - https://ssl-config.mozilla.org/#server=apache&version=2.4.57&config=intermediate&openssl=3.0.8&ocsp=false&guideline=5.7

However the `SSLCipherSuite` value in both is exactly the same.

**Comment by gstrauss** [comment]
I have a hunch that the site is built/generated from guideline 5.7, as indicated by the comment at the top of both of the lines you provided.  The site would need to be rebuilt/regenerated against guideline 5.6 to provide that information.

Guideline version is not a configurable option on the generated page.

I am not convinced this is feature that should be provided by the site, though it might be nice to document how end-users might regenerate the site from source control to access older guidelines.  Note that Guideline 5.7 is over 4 years old, so it is not like there are frequent changes being made to the guidelines.

**Comment by janbrasna** [comment]
At some point in the past the permalink was actually generated for it to be a "permalink", i.e. to be able to open the config in the state it was exported originally, and I understand the sentiment to expect for the link to work. (Or, at least make it extremely visible that you're coming from an old link, and what you see is the _current_ config instead…)

However since then a handful of breaking changes in the spec structure limited the compatibility and at some point only the `latest.json` symlink was being loaded into the app.

It may be trivial to add this so I keep it open if someone has the appetite to support arbitrary version refs, at least silently accepting any version in the query string and showing the latest config instead without any warning feels like a unfortunate mishap. (I don't expect this to ever be a consumer-facing choice, but when the time comes for a new spec version, people still may need to access the old permalinks to compare what's different to the current outputs etc., so as well as I'd love to see the current version of the specs visibly shown in the UI, I'm not exactly against being able to read older configs based on the query string and rendering those as a best effort.)

**Comment by janbrasna** [comment]
The other thing is… some of the minor version guidelines were superseded because they contained a bug — so they shouldn't really be used… so it's not an exactly simple topic.

**Comment by gstrauss** [comment]
Would it be feasible to have multiple github pages?  e.g. https://ssl-config.mozilla.org/spec-5.6/...  Then, a new spec would generate to a new location and the main page would simply redirect to the latest spec.

**Comment by gstrauss** [comment]
`src/templates/index.ejs` already includes `build <%= htmlWebpackPlugin.options.revision %>` with the git SHA1 revision, and this is already listed in the footer of `index.html` as, e.g. [build cab5c12](https://github.com/mozilla/ssl-config-generator/commit/cab5c12), generated 2024-12-06

If we generated the site off of the tags, then the site would at a given tag revision would be be loadable with a link into build/ (or docs/ if preferred).  That is one way to serve the site directly from the repository.  Creating a tarball of the build artifacts at a given tag is another option.

**Comment by gstrauss** [comment]
FYI: older versions of the site are available at archive.org in the Wayback Machine
https://web.archive.org/web/20240301000000*/https://ssl-config.mozilla.org/

**Comment by gstrauss** [comment]
Looking at the code in `src/js/state.js`, it is a possibility for the code to be modified to read all the guidelines and to render the site using current templates and data from older json guidelines.  The current URL generated includes `&guideline=5.7` in the URL fragment, though I did not see that parameter included in the 2019 version of the site pulled from archive.org, so it was apparently added some time in between.

This would be a coarse way to *somewhat* support older guidelines, but would not guarantee an exact replication of what was produced at a prior point in time.  For an attempt at exact replication, download the source, `git checkout` the desired revision, and `npm run build` the site.   ... should we consider including the site git SHA in the URL fragment, in addition to `&guideline=5.7`?

**Comment by gstrauss** [comment]
I have removed the 'help wanted' tag since there are numerous different approaches which could be taken, and it would be better to discuss design changes such as versioning and deployment workflows to provide better direction on what might be one of the acceptable solutions.

I might experiment with rendering the current site using data from older guideline version taken from the URL.

**Comment by gstrauss** [comment]
I looked through the guidelines from 5.0 to 5.7 and the *only* substantive difference in the guidelines exposed in ssl-config-generator is the change from 5.6 to 5.7 which added DHE-RSA-CHACHA20-POLY1305.  (There was a change in the naming of 'secp256r1' to 'prime256v1', but curve names were only recently exposed in the ssl-config-generator in what will likely be tagged 5.7.2, and refers to the same curve.)  There were a small number of other changes in the guidelines, but those changes were not data exposed in ssl-config-generator output.

While I have an experimental commit in a development branch
https://github.com/gstrauss/ssl-config-generator/tree/multi-guideline
which supports guidelines 5.0 to 5.7, I think it is completely unnecessary bloat to package all the old guidelines.

If you need to see the output from 5.6, then the Wayback Machine should suffice.

Instead, I think a workaround here is to detect if `guideline=` requested in the URL does not match the current version of the guidelines, and to correct it in the URL fragment and/or add a note to the page warning the user that the guidelines have been updated since the link they followed was last generated.  The HTTP response of the two links in @jerrykan's original post has the same content.  Only the URL in the address bar remains different (`&guideline=5.6` vs `&guideline=5.7`) because the URL fragment is not updated on initial page load.

We might also add something to document that it is not a permalink, but rather a link with the input options pre-selected.

We might also add a date=YYYYMMDD to the generated link, too, for use in selecting a snapshot of the ssl-config-generator from the Wayback Machine.

From a practical security perspective, I am not convinced this permalink feature should be implemented.  If someone is visiting ssl-config-generator, the current guidance is what should be evaluated and considered by the visitor.

What are your thoughts and opinions?

**Comment by gstrauss** [comment]
I pushed a change which updates the URL fragment for visitors with old guideline links.
The URL now matches the content, effectively "redirecting" from an old link to a new link.

Regarding the UX, I think we should remove `&guideline=5.7` from the URL, replace it with the SHA of the commit and perhaps a date, and *add* a separate line below that link with a link to the guidelines used when generating the page, i.e. https://ssl-config.mozilla.org/guidelines/5.7.json

**Comment by jerrykan** [comment]
Hello @gstrauss, unfortunately this doesn't really solve the problem. I have been using the "permalinks" for documentation purposes (ie. including the link as a reference in commit messages when make infrastructure changes, etc.) with the expectation that I could see the original guidelines. Maybe I was putting to much faith in the links being permanent.

Updating the URL fragment doesn't seem to solve any specific problem. If a user is requesting a specific guideline version, then redirecting them to the latest isn't particularly useful.

Thanks for mentioning the WayBack machine, while not ideal (it requires a bit of effort to trawl through all the snapshot to find the correct guideline version), I'll keep it in mind for the future.

It would be great if the old guidelines were supported via the web interface, but I also understand if this will be closed as "wont fix". If that is the case though I would suggest removing the link from the generated comment, and removing the `guideline` parameter from the URL so that people don't get the wrong idea.

**Comment by gstrauss** [comment]
> I have been using the "permalinks" for documentation purposes (ie. including the link as a reference in commit messages when make infrastructure changes, etc.) with the expectation that I could see the original guidelines. Maybe I was putting to much faith in the links being permanent.

I appreciate the response and understand where you're coming from.  I agree that the UX should be clearer here.

That said, ssl-config-generator is trying to provide *security* guidelines, and I personally feel strongly that when someone visits the site, they should get *current* security guidelines, and are never accidentally given out-dated security guidelines.  

While *you* are using the link to try to get a historical version, if someone else writes a blog and links to the nginx config, that link includes the guideline version and I do not want blog readers 10 years in the future to follow the link from that third-party blog to get 10-year-old guidance and not realize the guidance is out-dated.

**Comment by gstrauss** [comment]
@jerrykan please do re-read my earlier comment about how (very few) substantive changes which have been made to the guidelines between v5.0 and v5.7.  The changes in the site rendering for a specific server may have changed more, but the underlying guidelines have changed very little, only adding `DHE-RSA-CHACHA20-POLY1305` to guideline v5.7.

I think you're interested in the site rendering which includes both the underlying guideline version as well as the code which produces the configuration.  My recent change does not re-render the site using the code from whenever you visited the site a few years ago.  That information is not available in the URL link.  It never was a proper permalink and we should try to make that more clear in the UX.

**Comment by gstrauss** [comment]
In order to make the link look less like a permalink, what do you think about prefixing with something like `# latest: https://...` ? perhaps even without removing `&guideline=5.7`

Current:
```
# generated 2024-12-12, Mozilla Guideline v5.7, nginx 1.27.3, OpenSSL 3.4.0, modern config
# https://ssl-config.mozilla.org/#server=nginx&version=1.27.3&config=modern&openssl=3.4.0&guideline=5.7
```

Proposed:
```
# generated 2024-12-12, Mozilla Guideline v5.7, nginx 1.27.3, OpenSSL 3.4.0, modern config
# latest: https://ssl-config.mozilla.org/#server=nginx&version=1.27.3&config=modern&openssl=3.4.0&guideline=5.7
```

**Comment by gene1wood** [comment]
@gstrauss and I discussed this issue this morning.

Here's what we came up with (Glenn, correct me if I'm not capturing this correctly)

The SSL Config Generator has essentially 2 different "versions" that might matter. One is the version of the guidelines, which is what that argument in the permalink is for and is meant to map to the version of the recommendation, which the SSL Config Generator is trying to use as it's basis for rendering configurations. This version can be seen in https://wiki.mozilla.org/Security/Server_Side_TLS#Version_History . The second is the version of the SSL Config Generator itself. This would be changes to how the generator functions or changes to specific configuration logic based on changes to server software. We don't really track this version and I'm seeing that we're kind of conflating the two versions (for example with [this 5.7.1 release](https://github.com/mozilla/ssl-config-generator/blob/master/src/static/guidelines/CHANGELOG.md#571---2024-01-04) which captures new SSL Config Generator functionality but which doesn't relate to a change in the actual guidelines that sit behind the generator.

This dual/conflated versioning is confusing and we should probably do something to clarify this. Maybe we do reserve the `patch` portion of the semver for changes to the generator and restrict the guidelines to only using `major` and `minor`. This would follow the `5.7.1` release example. I'll start a new issue to figure this versioning issue out.

From a permalink perspective we only have an interest in capturing the guidelines version, not the SSL Config Generator version. To illustrate by example :

When Mozilla's recommendations change about how best to securely setup server side TLS, we want to capture that change over time and enable people to easily get to the old or new recommendations via permalink. So when we added the `TLS_DHE_RSA_WITH_CHACHA20_POLY1305_SHA256` cipher we moved from guidelines version `5.6` to `5.7` and this should be accessible via permalink. In contrast when the SSL Config Generator moved to using Webpack 5 (an under the hood change), added support for `stunnel` and fixed the `TLSStaplingCache` proftpd setting which was a bug in the generator, we don't have any interest in making sure the configs rendered before these changes with the 5.7 guidelines are accessible by their own permalink.

We are going to be making more drastic guideline changes coming up, likely a version 6, and this will make it really important that a permalink to the old 5.7 guidelines in the SSL Config Generator is different from the version 6 guidelines. So we'll want to solve this problem.

To echo what @gstrauss said above, it's important that users don't end up using out of date guidelines because they're following a permalink to an old guideline version, so I think a good solution to this would be for any page rendered from not-the-latest guidelines, there's a warning banner on the page showing the user that they're looking at not-the-latest guidelines and a link to the equivalent permalink for the newest guidelines.

@gstrauss indicated that it should be very possible with a relatively small code change to render a guideline-version-specific page based on the `guideline` query argument in the permalink. Glenn, do you want to open an issue to track that work?

Again, Glenn please add any corrections/tweaks to this.

@jerrykan based on all of this, would the following situation sound ok with you

* The permalink renders the version of the guidelines in the `guidelines` query argument, creating a config with the same functionality in the server config as when the permalink was first created
* The byte for byte content of the config that's generated might be different (for example addition of comments, change to a directive that was incorrect previously and didn't actually correctly render the, for example, 5.7 guidelines)

**Comment by gstrauss** [comment]
> @gstrauss indicated that it should be very possible with a relatively small code change to render a guideline-version-specific page based on the guideline query argument in the permalink. Glenn, do you want to open an issue to track that work?

Not needed.  I will push a change shortly with this functionality, EXCEPT there is still a work-item for how to indicate to user that the page is rendering an older version of the guideline.

> To echo what @gstrauss said above, it's important that users don't end up using out of date guidelines because they're following a permalink to an old guideline version, so I think a good solution to this would be for any page rendered from not-the-latest guidelines, there's a warning banner on the page showing the user that they're looking at not-the-latest guidelines and a link to the equivalent permalink for the newest guidelines.

TODO: any concrete suggestions how/where to do this on the page, besides using a `<blink>` tag? ;)
(This issue (#240) can track that, or a new issue can be created.)

---

> @jerrykan based on all of this, would the following situation sound ok with you
>
> * The permalink renders the version of the guidelines in the guideline query argument, creating a config with the same functionality in the server config as when the permalink was first created
> * The byte for byte content of the config that's generated might be different (for example addition of comments, change to a directive that was incorrect previously and didn't actually correctly render the, for example, 5.7 guidelines)

@gene1wood that is confusing to me.  Your first bullet point "creating a config with the same functionality" might not be accurate.  A more precise statement would be something along the lines of "The site will be rendered based on the guideline version specified and using the current ssl-config-generator code."  For site renderings using prior versions of the ssl-config-generator code, a client-side javascript application, the Internet Archive might be used instead.

**Comment by gstrauss** [comment]
ssl-config-generator is not maintained to an ISO standard with rigorous vetting and change control, though it is (somewhat) maintained by security professionals *volunteering* their time and expertise, and acting in a best effort capacity as time allows.  I personally do not think we should rubber stamp various paper-pushers misusing this site via a permalink providing dubious guarantees incorrectly presumed by said paper-pushers.

That is why I suggested removing the 'guideline' attribute from the query string and always providing the latest guidelines here, which older versions of the site (including guidelines) available from the wayback machine on the Internet Archive.

That is my most desirable preference to making it clear what guarantees are provided by links to this site.

All that said, to keep things moving, I have coded up and will momentarily push the changes to support rendering the site using older versions of the guidelines, if specified in the URL -- even though that is not my most desirable preference.

**Comment by gstrauss** [comment]
Looks like I have to adjust the CSP.  The site worked locally, but now that it has been deployed, trying to use an older version of the guidelines results in:
`Content-Security-Policy: The page’s settings blocked the loading of a resource (connect-src) at https://ssl-config.mozilla.org/guidelines/5.2.json because it violates the following directive: “connect-src https://www.google-analytics.com/”`

**Comment by gstrauss** [comment]
Update: specifying old guideline in the URL works now.  Sorry for the extra noise.

**Comment by jerrykan** [comment]
> [@jerrykan](https://github.com/jerrykan) based on all of this, would the following situation sound ok with you
> 
>     * The permalink renders the version of the guidelines in the `guideline` query argument, creating a config with the same functionality in the server config as when the permalink was first created
> 
>     * The byte for byte content of the config that's generated might be different (for example addition of comments, change to a directive that was incorrect previously and didn't actually correctly render the, for example, 5.7 guidelines)

Yes, this would seem to be a reasonable solution. I doubt many people are copy-n-pasting the contents of the guidelines without make _some_ modifications themselves. So if the comments or formatting a slightly different I don't think that is a big deal.

---

> TODO: any concrete suggestions how/where to do this on the page, besides using a `<blink>` tag? ;)
> (This issue ([#240](https://github.com/mozilla/ssl-config-generator/issues/240)) can track that, or a new issue can be created.)

I think a simple `<div>` with a brightly coloured background contain text explaining that the user is looking at a configuration for an old guideline version and a link to the latest version would work well. Something like the following rough mock-up:

![Image](https://github.com/user-attachments/assets/8f6c21d6-b26e-4526-8076-d4e5568df7de)
